"""
extract_features_sdxl_unclip.py
===============================
Exact replication of the original extract_features_sdxl_unclip.ipynb logic.

Extracts SDXL OpenCLIP (ViT-bigG-14) image embeddings from PNG images
previously generated by save_images.py.

Input:
  - Data/nsd/subj0{sub}/train_img/{i}.png    (425x425 RGB PNGs)
  - Data/nsd/subj0{sub}/test_img/{i}.png     (425x425 RGB PNGs)
  - checkpoints/sdxl_unclip/open_clip_pytorch_model.bin

Output (saved into Data/nsd/subj0{sub}/):
  - nsd_sdxl_clip_train_sub{sub}.npy          (N_train, 256, 1664)
  - nsd_sdxl_clip_pool_train_sub{sub}.npy     (N_train, 1664)
  - nsd_sdxl_clip_test_sub{sub}.npy           (N_test,  256, 1664)
  - nsd_sdxl_clip_pool_test_sub{sub}.npy      (N_test,  1664)

Usage:
  python SynBrain/data/extract_features_sdxl_unclip.py
"""

import sys
import os
import torch
import numpy as np
from PIL import Image
import torchvision.transforms.functional as TF
from torch.utils.data import DataLoader, Dataset

import argparse

# ==============================================================================
# Configuration (paths relative to this script)
# ==============================================================================
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.abspath(os.path.join(SCRIPT_DIR, '../../NSD/data'))
PROCESSED_DATA_DIR = os.path.join(BASE_DIR, 'nsd')

# Model checkpoint path
OPEN_CLIP_MODEL_PATH = os.path.abspath(os.path.join(BASE_DIR, '../checkpoints/sdxl_unclip/open_clip_pytorch_model.bin'))

DEFAULT_SUBJECTS = [1, 2, 5, 7]
DEFAULT_BATCH_SIZE = 300

parser = argparse.ArgumentParser(description="Extract SDXL OpenCLIP ViT-bigG-14 features")
parser.add_argument('--subjects', type=int, nargs='+', default=DEFAULT_SUBJECTS,
                    help='Subject numbers to process (default: 1 2 5 7)')
parser.add_argument('--batch_size', type=int, default=DEFAULT_BATCH_SIZE,
                    help=f'Batch size (default: {DEFAULT_BATCH_SIZE})')
args = parser.parse_args()

SUBJECTS = args.subjects
BATCH_SIZE = args.batch_size

# ==============================================================================
# Import SGM modules
# ==============================================================================
# Original notebook: sys.path.append('.../SynBrain/src/sdxl/generative_models')
# Original notebook: from generative_models.sgm.modules.encoders.modules import FrozenOpenCLIPImageEmbedder
SGM_MODULE_PATH = os.path.abspath(os.path.join(SCRIPT_DIR, '../../NSD/notes/SynBrain/src/sdxl'))
sys.path.append(SGM_MODULE_PATH)

try:
    from generative_models.sgm.modules.encoders.modules import FrozenOpenCLIPImageEmbedder
except ImportError as e:
    print(f"Error importing SGM modules: {e}")
    print(f"Expected SGM path: {SGM_MODULE_PATH}/generative_models/sgm/modules/encoders/modules.py")
    sys.exit(1)

# ==============================================================================
# Check model file
# ==============================================================================
if not os.path.exists(OPEN_CLIP_MODEL_PATH):
    print(f"ERROR: open_clip_pytorch_model.bin not found at: {OPEN_CLIP_MODEL_PATH}")
    print("Please download from: https://huggingface.co/laion/CLIP-ViT-bigG-14-laion2B-39B-b160k/resolve/main/open_clip_pytorch_model.bin")
    sys.exit(1)

# ==============================================================================
# Initialize model (matching the original notebook exactly)
# ==============================================================================
# tf32 data type is faster than standard float32
torch.backends.cuda.matmul.allow_tf32 = True
device = 'cuda' if torch.cuda.is_available() else 'cpu'

clip_img_embedder = FrozenOpenCLIPImageEmbedder(
    arch="ViT-bigG-14",
    version=OPEN_CLIP_MODEL_PATH,
    output_tokens=True,
    only_tokens=False,
)
clip_img_embedder.to(device).eval()

clip_seq_dim = 256
clip_emb_dim = 1664

# ==============================================================================
# Multilayer extraction via hooks
# ==============================================================================
# ViT-bigG-14 has 48 transformer blocks
# Select layers spread across depth for multilayer features
EXTRACT_LAYERS = [11, 23, 35, 47]  # early, mid-early, mid-late, last

# Access the underlying ViT transformer blocks
try:
    vit_model = clip_img_embedder.model.visual.transformer
    resblocks = vit_model.resblocks
    num_blocks = len(resblocks)
    print(f"ViT-bigG-14: {num_blocks} transformer blocks")
    print(f"Multilayer extraction layers: {EXTRACT_LAYERS}")
except Exception as e:
    print(f"Warning: Cannot access ViT internals for multilayer extraction: {e}")
    print("Will only save tokens and pooled features.")
    resblocks = None

# Hook storage
_intermediate_outputs = {}

def make_hook(layer_idx):
    def hook_fn(module, input, output):
        _intermediate_outputs[layer_idx] = output.detach()
    return hook_fn

# Register hooks
hooks = []
if resblocks is not None:
    for layer_idx in EXTRACT_LAYERS:
        if layer_idx < num_blocks:
            h = resblocks[layer_idx].register_forward_hook(make_hook(layer_idx))
            hooks.append(h)

# ==============================================================================
# Dataset class (matching the original notebook exactly)
# ==============================================================================
class CLIP_Image_Dataset(Dataset):
    def __init__(self, image_path):
        self.img_data = image_path   # 图像path

    def __getitem__(self, idx):
        img = Image.open(self.img_data[idx])  # 一张图像对应1个fmri
        img = TF.to_tensor(img).float()
        return img

    def __len__(self):
        return len(self.img_data)

# ==============================================================================
# Extract features
# ==============================================================================
for subj in SUBJECTS:
    save_path = os.path.join(PROCESSED_DATA_DIR, f'subj0{subj}')
    if not os.path.exists(save_path):
        print(f"Subject {subj} folder not found at {save_path}, skipping...")
        continue

    print(f"\nProcessing Subject {subj}...")

    for mode in ['train', 'test']:
        image_dir = os.path.join(save_path, f'{mode}_img')
        if not os.path.exists(image_dir):
            print(f"  {mode}_img not found, skipping...")
            continue

        # Build sorted file list: 0.png, 1.png, 2.png, ...
        num_images = len([f for f in os.listdir(image_dir) if f.endswith('.png')])
        image_paths = np.array([os.path.join(image_dir, f'{i}.png') for i in range(num_images)])
        print(f'  {mode.capitalize()} images: {image_paths.shape}')

        dataset = CLIP_Image_Dataset(image_paths)
        dataloader = DataLoader(dataset, batch_size=BATCH_SIZE, drop_last=False)

        all_tokens = []   # (B, 256, 1664)
        all_pooled = []   # (B, 1664)
        all_multi = []    # (B, L, 1664)

        for batch_i, image in enumerate(dataloader):
            print(f"  Extracting Batch {batch_i} / {mode}...")

            _intermediate_outputs.clear()

            with torch.no_grad():
                z, z_pool = clip_img_embedder(image.to(device))

            all_tokens.append(z.detach().cpu())
            all_pooled.append(z_pool.detach().cpu())

            # Collect multilayer CLS tokens from hooks
            if _intermediate_outputs:
                # ViT outputs: (seq_len, batch, dim) — CLS is token[0]
                multi_cls = []
                for layer_idx in sorted(_intermediate_outputs.keys()):
                    out = _intermediate_outputs[layer_idx]
                    # OpenCLIP ViT transformer output: (seq_len, batch, dim)
                    if out.dim() == 3 and out.shape[0] != image.shape[0]:
                        # (seq_len, B, D) format — CLS is out[0]
                        cls = out[0]  # (B, D)
                    else:
                        # (B, seq_len, D) format — CLS is out[:,0]
                        cls = out[:, 0]  # (B, D)
                    multi_cls.append(cls)
                multi_cls = torch.stack(multi_cls, dim=1)  # (B, L, D)
                all_multi.append(multi_cls.cpu())

            torch.cuda.empty_cache()

        if all_tokens:
            # 1. Tokens (256 patch tokens, last layer)
            zs = torch.cat(all_tokens, dim=0)
            out_clip = os.path.join(save_path, f'nsd_sdxl_clip_{mode}_sub{subj}.npy')
            np.save(out_clip, zs.numpy())
            print(f"  ✅ Tokens: {out_clip} shape={zs.shape}")
            del zs, all_tokens

            # 2. Pooled (CLS/pooled, last layer)
            zs_pool = torch.cat(all_pooled, dim=0)
            out_pool = os.path.join(save_path, f'nsd_sdxl_clip_pool_{mode}_sub{subj}.npy')
            np.save(out_pool, zs_pool.numpy())
            print(f"  ✅ Pooled: {out_pool} shape={zs_pool.shape}")
            del zs_pool, all_pooled

            # 3. Multilayer CLS tokens
            if all_multi:
                zs_multi = torch.cat(all_multi, dim=0)
                out_multi = os.path.join(save_path, f'nsd_sdxl_clip_multi_{mode}_sub{subj}.npy')
                np.save(out_multi, zs_multi.numpy())
                print(f"  ✅ Multi:  {out_multi} shape={zs_multi.shape}")
                del zs_multi, all_multi

# Remove hooks
for h in hooks:
    h.remove()

print("\nDone. Feature extraction completed successfully!")
