"""
extract_features.py
===================
A unified script to extract image features (DINOv2, Qwen3-VL, ResNet, SAM, SDXL OpenCLIP)
from PNG images previously generated by save_images.py.

Usage examples:
  python src/data/extract_features.py --model dinov2_vitl14 --subjects 1
  python src/data/extract_features.py --model resnet50 --subjects 1
  python src/data/extract_features.py --model sdxl_clip --subjects 1
  python src/data/extract_features.py --model qwen3vl --subjects 1 --batch_size 8
"""

import argparse
import os
import sys
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image
from tqdm import tqdm
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms, models
import torchvision.transforms.functional as TF

# ==============================================================================
# Configuration Registry
# ==============================================================================
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.abspath(os.path.join(SCRIPT_DIR, '../../NSD/data'))
PROCESSED_DATA_DIR = os.path.join(BASE_DIR, 'nsd')

# ImageNet normalization constants
IMAGENET_MEAN = (0.485, 0.456, 0.406)
IMAGENET_STD = (0.229, 0.224, 0.225)

MODEL_CONFIGS = {
    'dinov2_vitl14': {
        'model_type': 'dinov2',
        'model_name': 'dinov2_vitl14',
        'file_prefix': 'dinov2_vitl14',
        'batch_size': 128,
        'default_layers': None,  # Calculated dynamically: [5, 11, 17, 23]
        'has_tokens': True,
        'multi_suffix': '_multilayer_'
    },
    'dinov2_vitb14': {
        'model_type': 'dinov2',
        'model_name': 'dinov2_vitb14',
        'file_prefix': 'dinov2_vitb14',
        'batch_size': 128,
        'default_layers': None,  # Calculated dynamically: [2, 5, 8, 11]
        'has_tokens': True,
        'multi_suffix': '_multilayer_'
    },
    'dinov2_vits14': {
        'model_type': 'dinov2',
        'model_name': 'dinov2_vits14',
        'file_prefix': 'dinov2_vits14',
        'batch_size': 128,
        'default_layers': None,
        'has_tokens': True,
        'multi_suffix': '_multilayer_'
    },
    'dinov2_vitg14': {
        'model_type': 'dinov2',
        'model_name': 'dinov2_vitg14',
        'file_prefix': 'dinov2_vitg14',
        'batch_size': 128,
        'default_layers': None,
        'has_tokens': True,
        'multi_suffix': '_multilayer_'
    },
    'qwen3vl': {
        'model_type': 'qwen3vl',
        'model_name': 'Qwen/Qwen3-VL-Embedding-2B',
        'file_prefix': 'qwen3vl',
        'batch_size': 8,
        'default_layers': [6, 13, 20, 27],
        'has_tokens': False,
        'multi_suffix': '_multi_'
    },
    'resnet50': {
        'model_type': 'resnet',
        'model_name': 'resnet50',
        'file_prefix': 'resnet50',
        'batch_size': 64,
        'default_layers': ['layer1', 'layer2', 'layer3', 'layer4'],
        'has_tokens': False,
        'multi_suffix': '_multi_'
    },
    'resnet101': {
        'model_type': 'resnet',
        'model_name': 'resnet101',
        'file_prefix': 'resnet101',
        'batch_size': 64,
        'default_layers': ['layer1', 'layer2', 'layer3', 'layer4'],
        'has_tokens': False,
        'multi_suffix': '_multi_'
    },
    'sam-vit-base': {
        'model_type': 'sam',
        'model_name': 'facebook/sam-vit-base',
        'file_prefix': 'sam-vit-base',
        'batch_size': 4,
        'default_layers': [2, 5, 8, 11],
        'has_tokens': False,
        'multi_suffix': '_multi_'
    },
    'sam-vit-huge': {
        'model_type': 'sam',
        'model_name': 'facebook/sam-vit-huge',
        'file_prefix': 'sam-vit-huge',
        'batch_size': 2,
        'default_layers': [7, 15, 23, 31],
        'has_tokens': False,
        'multi_suffix': '_multi_'
    },
    'sdxl_clip': {
        'model_type': 'sdxl_clip',
        'model_name': 'ViT-bigG-14',
        'file_prefix': 'sdxl_clip',
        'batch_size': 300,
        'default_layers': [11, 23, 35, 47],
        'has_tokens': True,
        'multi_suffix': '_multi_'
    }
}

# ==============================================================================
# Unified Dataset Class
# ==============================================================================
class UnifiedImageDataset(Dataset):
    def __init__(self, image_paths, model_type, transform_or_processor=None):
        self.image_paths = image_paths
        self.model_type = model_type
        self.transform_or_processor = transform_or_processor

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        img = Image.open(img_path)
        
        if self.model_type in ['dinov2', 'resnet']:
            img = img.convert('RGB')
            if self.transform_or_processor:
                img = self.transform_or_processor(img)
            return img
        elif self.model_type == 'sam':
            img = img.convert('RGB')
            inputs = self.transform_or_processor(images=img, return_tensors="pt")
            return inputs['pixel_values'].squeeze(0)
        elif self.model_type == 'sdxl_clip':
            img = img.convert('RGB')
            img = TF.to_tensor(img).float()
            return img
        else:
            raise ValueError(f"Unsupported model_type in dataset: {self.model_type}")

# ==============================================================================
# Helper functions for loading and processing
# ==============================================================================
def load_model_and_processor(model_key, model_path_override=None, device='cuda'):
    config = MODEL_CONFIGS[model_key]
    model_type = config['model_type']
    model_name_or_path = model_path_override if model_path_override else config['model_name']
    
    model = None
    processor_or_transform = None
    
    if model_type == 'dinov2':
        print(f"Loading {model_name_or_path} from torch.hub...")
        model = torch.hub.load('facebookresearch/dinov2', model_name_or_path)
        model = model.to(device).eval()
        
        # DINOv2 transform
        processor_or_transform = transforms.Compose([
            transforms.Resize(224, interpolation=transforms.InterpolationMode.BICUBIC),
            transforms.CenterCrop(224),
            transforms.ToTensor(),
            transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
        ])
        
    elif model_type == 'resnet':
        print(f"Loading {model_name_or_path} from torchvision...")
        if model_name_or_path == 'resnet50':
            weights = models.ResNet50_Weights.IMAGENET1K_V2
            model = models.resnet50(weights=weights)
        elif model_name_or_path == 'resnet101':
            weights = models.ResNet101_Weights.IMAGENET1K_V2
            model = models.resnet101(weights=weights)
        else:
            raise ValueError(f"Unknown resnet model: {model_name_or_path}")
            
        model = model.to(device).eval()
        
        # ResNet transform
        processor_or_transform = transforms.Compose([
            transforms.Resize(256, interpolation=transforms.InterpolationMode.BILINEAR),
            transforms.CenterCrop(224),
            transforms.ToTensor(),
            transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
        ])
        
    elif model_type == 'sam':
        from transformers import SamModel, SamProcessor
        print(f"Loading {model_name_or_path} from transformers...")
        processor_or_transform = SamProcessor.from_pretrained(model_name_or_path)
        model = SamModel.from_pretrained(model_name_or_path)
        model = model.to(device).eval()
        
    elif model_type == 'sdxl_clip':
        # Append SGM path
        script_dir = os.path.dirname(os.path.abspath(__file__))
        sgm_path = os.path.abspath(os.path.join(script_dir, '../../NSD/notes/SynBrain/src/sdxl'))
        if sgm_path not in sys.path:
            sys.path.append(sgm_path)
            
        from generative_models.sgm.modules.encoders.modules import FrozenOpenCLIPImageEmbedder
        
        # Determine weights path
        if model_path_override:
            open_clip_model_path = model_path_override
        else:
            base_data_dir = os.path.abspath(os.path.join(script_dir, '../../NSD/data'))
            open_clip_model_path = os.path.abspath(os.path.join(base_data_dir, '../checkpoints/sdxl_unclip/open_clip_pytorch_model.bin'))
            
        if not os.path.exists(open_clip_model_path):
            print(f"ERROR: open_clip_pytorch_model.bin not found at: {open_clip_model_path}")
            print("Please download from: https://huggingface.co/laion/CLIP-ViT-bigG-14-laion2B-39B-b160k/resolve/main/open_clip_pytorch_model.bin")
            sys.exit(1)
            
        print(f"Loading FrozenOpenCLIPImageEmbedder from: {open_clip_model_path}...")
        model = FrozenOpenCLIPImageEmbedder(
            arch="ViT-bigG-14",
            version=open_clip_model_path,
            output_tokens=True,
            only_tokens=False,
        )
        model = model.to(device).eval()
        processor_or_transform = None
        
    elif model_type == 'qwen3vl':
        from transformers import Qwen3VLProcessor
        print(f"Loading {model_name_or_path}...")
        
        try:
            from transformers import AutoModel
            model = AutoModel.from_pretrained(
                model_name_or_path,
                trust_remote_code=True,
                torch_dtype=torch.float16,
            ).to(device).eval()
        except Exception:
            from transformers import Qwen3VLForConditionalGeneration
            model = Qwen3VLForConditionalGeneration.from_pretrained(
                model_name_or_path,
                torch_dtype=torch.float16,
                output_hidden_states=True,
            ).to(device).eval()
            
        processor_or_transform = Qwen3VLProcessor.from_pretrained(
            model_name_or_path,
            padding_side='right',
        )
        
    else:
        raise ValueError(f"Unsupported model_type: {model_type}")
        
    return model, processor_or_transform

def extract_qwen_batch(model, processor, image_paths, layers, device):
    conversations_batch = []
    for img_path in image_paths:
        conversation = [
            {"role": "system", "content": [{"type": "text", "text": "Represent the user's input."}]},
            {"role": "user", "content": [
                {"type": "image", "image": f"file://{img_path}",
                 "min_pixels": 4 * 28 * 28, "max_pixels": 1800 * 28 * 28},
            ]}
        ]
        conversations_batch.append(conversation)

    from qwen_vl_utils import process_vision_info
    
    texts = processor.apply_chat_template(
        conversations_batch, add_generation_prompt=True, tokenize=False
    )
    
    all_images = []
    for conv in conversations_batch:
        try:
            imgs, _, _ = process_vision_info(
                conv, return_video_metadata=True, return_video_kwargs=True
            )
            if imgs:
                all_images.extend(imgs)
        except Exception:
            imgs, _ = process_vision_info(conv)
            if imgs:
                all_images.extend(imgs)
                
    inputs = processor(
        text=texts,
        images=all_images if all_images else None,
        truncation=True,
        max_length=8192,
        padding=True,
        return_tensors='pt',
    )
    inputs = {k: v.to(device) for k, v in inputs.items()}
    
    with torch.no_grad(), torch.amp.autocast('cuda', enabled=(device == 'cuda')):
        outputs = model(**inputs, output_hidden_states=True)
        
        if hasattr(outputs, 'last_hidden_state'):
            last_hidden = outputs.last_hidden_state
        elif hasattr(outputs, 'hidden_states') and outputs.hidden_states is not None:
            last_hidden = outputs.hidden_states[-1]
            
        attn_mask = inputs['attention_mask']
        
        # Helper function
        def pooling_last(hidden_state, attention_mask):
            flipped = attention_mask.flip(dims=[1])
            last_positions = flipped.argmax(dim=1)
            col = attention_mask.shape[1] - last_positions - 1
            row = torch.arange(hidden_state.shape[0], device=hidden_state.device)
            return hidden_state[row, col]
            
        pooled = pooling_last(last_hidden, attn_mask)
        pooled = F.normalize(pooled.float(), p=2, dim=-1)
        
        multi_embeddings = None
        if hasattr(outputs, 'hidden_states') and outputs.hidden_states is not None:
            multi_list = []
            for layer_idx in layers:
                if layer_idx + 1 < len(outputs.hidden_states):
                    layer_hidden = outputs.hidden_states[layer_idx + 1]
                    layer_pooled = pooling_last(layer_hidden, attn_mask)
                    layer_pooled = F.normalize(layer_pooled.float(), p=2, dim=-1)
                    multi_list.append(layer_pooled)
            if multi_list:
                multi_embeddings = torch.stack(multi_list, dim=1)
                
    return pooled, multi_embeddings

# ==============================================================================
# Main function
# ==============================================================================
def parse_args():
    parser = argparse.ArgumentParser(description="Unified Feature Extraction Script")
    parser.add_argument('--model', type=str, required=True, choices=list(MODEL_CONFIGS.keys()),
                        help="Model to extract features from.")
    parser.add_argument('--subjects', type=int, nargs='+', default=[1, 2, 5, 7],
                        help="Subject numbers to process (default: 1 2 5 7)")
    parser.add_argument('--batch_size', type=int, default=None,
                        help="Override default batch size.")
    parser.add_argument('--layers', type=str, nargs='+', default=None,
                        help="Override layer indices/names for multilayer extraction.")
    parser.add_argument('--device', type=str, default='',
                        help="Device to run on (default: cuda if available, else cpu)")
    parser.add_argument('--model_path', type=str, default=None,
                        help="Override default model weights path / Hugging Face repo path.")
    return parser.parse_args()

def main():
    args = parse_args()
    
    # ── Device Setup ──
    device = args.device if args.device else ('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Using device: {device}")
    torch.backends.cuda.matmul.allow_tf32 = True
    
    # ── Load Config ──
    model_key = args.model
    config = MODEL_CONFIGS[model_key]
    model_type = config['model_type']
    file_prefix = config['file_prefix']
    
    # ── Override Config Parameters ──
    batch_size = args.batch_size if args.batch_size is not None else config['batch_size']
    
    # Layers parsing
    if args.layers is not None:
        # If layers are integers, convert them, otherwise keep as strings
        layers = []
        for l in args.layers:
            try:
                layers.append(int(l))
            except ValueError:
                layers.append(l)
    else:
        layers = config['default_layers']
        
    # ── Load Model and Processor/Transform ──
    model, processor_or_transform = load_model_and_processor(
        model_key, model_path_override=args.model_path, device=device
    )
    
    # DINOv2 layers setup if default layers needed calculation
    if model_type == 'dinov2' and layers is None:
        num_layers = len(model.blocks)
        step = num_layers // 4
        layers = [step - 1, step * 2 - 1, step * 3 - 1, num_layers - 1]
        print(f"DINOv2 layers calculated: {layers}")
        
    print(f"Batch size: {batch_size}")
    print(f"Selected layers for multilayer extraction: {layers}")
    
    # Hook storage setup for models using hooks
    intermediate_outputs = {}
    hooks = []
    
    def get_activation(name):
        def hook(m, input, output):
            intermediate_outputs[name] = output.detach()
        return hook
        
    if model_type == 'resnet':
        for layer_name in layers:
            layer_module = getattr(model, layer_name)
            hooks.append(layer_module.register_forward_hook(get_activation(layer_name)))
            
    elif model_type == 'sdxl_clip':
        # OpenCLIP visual transformer blocks
        try:
            vit_model = model.model.visual.transformer
            resblocks = vit_model.resblocks
            for idx in layers:
                if idx < len(resblocks):
                    hooks.append(resblocks[idx].register_forward_hook(get_activation(idx)))
            print(f"OpenCLIP hooks registered successfully on layers: {layers}")
        except Exception as e:
            print(f"Warning: Cannot access OpenCLIP ViT internals for hooks: {e}")
            hooks = []
                # ── Loop over subjects ──
    for subj in args.subjects:
        save_path = os.path.join(PROCESSED_DATA_DIR, f'subj0{subj}')
        if not os.path.exists(save_path):
            print(f"\nSubject {subj} folder not found at {save_path}, skipping...")
            continue
            
        print(f"\n{'='*60}")
        print(f"Processing Subject {subj}...")
        print(f"{'='*60}")
        
        for mode in ['train', 'test']:
            image_dir = os.path.join(save_path, f'{mode}_img')
            if not os.path.exists(image_dir):
                print(f"  {mode}_img not found, skipping...")
                continue
                
            # Build sorted file list: 0.png, 1.png, 2.png, ...
            num_images = len([f for f in os.listdir(image_dir) if f.endswith('.png')])
            image_paths = [os.path.join(image_dir, f'{i}.png') for i in range(num_images)]
            print(f'  {mode.capitalize()} images: {num_images}')
            
            # Special fast-path for Qwen3-VL due to different batch tokenization logic
            if model_type == 'qwen3vl':
                # Get dummy shape for Qwen3-VL
                dummy_paths = [image_paths[0]]
                dummy_pooled, dummy_multi = extract_qwen_batch(model, processor_or_transform, dummy_paths, layers, device)
                
                out_pool_path = os.path.join(save_path, f'nsd_{file_prefix}_pool_{mode}_sub{subj}.npy')
                pool_mmap = np.lib.format.open_memmap(out_pool_path, mode='w+', dtype=np.float16, shape=(num_images, dummy_pooled.shape[1]))
                
                multi_mmap = None
                if dummy_multi is not None:
                    out_multi_path = os.path.join(save_path, f'nsd_{file_prefix}{config["multi_suffix"]}{mode}_sub{subj}.npy')
                    multi_mmap = np.lib.format.open_memmap(out_multi_path, mode='w+', dtype=np.float16, shape=(num_images, dummy_multi.shape[1], dummy_multi.shape[2]))
                
                for start_idx in tqdm(range(0, num_images, batch_size), desc=f"  Extracting {mode}"):
                    end_idx = min(start_idx + batch_size, num_images)
                    batch_paths = image_paths[start_idx:end_idx]
                    
                    pooled, multi = extract_qwen_batch(model, processor_or_transform, batch_paths, layers, device)
                    pool_mmap[start_idx:end_idx] = pooled.cpu().half().numpy()
                    if multi is not None and multi_mmap is not None:
                        multi_mmap[start_idx:end_idx] = multi.cpu().half().numpy()
                        
                    torch.cuda.empty_cache()
                    
                del pool_mmap
                if multi_mmap is not None:
                    del multi_mmap
                    
                print(f"  ✅ Saved: {out_pool_path} (size={os.path.getsize(out_pool_path)/1e6:.1f}MB)")
                if dummy_multi is not None:
                    print(f"  ✅ Saved: {out_multi_path} (size={os.path.getsize(out_multi_path)/1e6:.1f}MB)")
                continue
                
            # Dataset and DataLoader for other models
            dataset = UnifiedImageDataset(image_paths, model_type, transform_or_processor=processor_or_transform)
            
            # Use smaller number of workers for SAM to prevent multiprocessing overhead / memory issues
            num_workers = 2 if model_type == 'sam' else 4
            dataloader = DataLoader(dataset, batch_size=batch_size, drop_last=False, num_workers=num_workers, pin_memory=True)
            
            # Run a dummy batch forward pass to dynamically compute feature shapes
            dummy_img = dataset[0].unsqueeze(0).to(device)
            intermediate_outputs.clear()
            with torch.no_grad(), torch.amp.autocast('cuda', enabled=(device == 'cuda')):
                if model_type == 'dinov2':
                    output = model.forward_features(dummy_img)
                    cls_token = output['x_norm_clstoken']
                    patch_tokens = output['x_norm_patchtokens']
                    full_features = torch.cat([cls_token.unsqueeze(1), patch_tokens], dim=1)
                    
                    intermediate = model.get_intermediate_layers(dummy_img, n=layers, reshape=False, return_class_token=True)
                    multi_features = torch.stack([
                        torch.cat([c.unsqueeze(1), p], dim=1) for p, c in intermediate
                    ], dim=1)
                    
                elif model_type == 'resnet':
                    x = model.conv1(dummy_img)
                    x = model.bn1(x)
                    x = model.relu(x)
                    x = model.maxpool(x)
                    x = model.layer1(x)
                    x = model.layer2(x)
                    x = model.layer3(x)
                    x = model.layer4(x)
                    x_pool = model.avgpool(x)
                    x_pool = torch.flatten(x_pool, 1)
                    
                    multi_features_list = []
                    for layer_name in layers:
                        feat = intermediate_outputs[layer_name]
                        feat_pool = F.adaptive_avg_pool2d(feat, (1, 1))
                        feat_pool = torch.flatten(feat_pool, 1)
                        pad_size = 2048 - feat_pool.shape[1]
                        if pad_size > 0:
                            feat_pool = F.pad(feat_pool, (0, pad_size))
                        multi_features_list.append(feat_pool)
                    multi_features = torch.stack(multi_features_list, dim=1)
                    cls_token = x_pool
                    full_features = None
                    
                elif model_type == 'sam':
                    outputs = model.vision_encoder(dummy_img, output_hidden_states=True)
                    image_embeddings = outputs.last_hidden_state
                    pooled = F.adaptive_avg_pool2d(image_embeddings, (1, 1)).squeeze(-1).squeeze(-1)
                    
                    multi_list = []
                    for idx in layers:
                        if idx < len(outputs.hidden_states):
                            hidden_state = outputs.hidden_states[idx]
                            if hidden_state.dim() == 4:
                                if hidden_state.shape[-1] == model.config.vision_config.hidden_size:
                                    hidden_state = hidden_state.permute(0, 3, 1, 2)
                                layer_pooled = F.adaptive_avg_pool2d(hidden_state, (1, 1)).squeeze(-1).squeeze(-1)
                            elif hidden_state.dim() == 3:
                                layer_pooled = hidden_state.mean(dim=1)
                            else:
                                raise ValueError(f"Unexpected hidden state shape: {hidden_state.shape}")
                            multi_list.append(layer_pooled)
                    multi_features = torch.stack(multi_list, dim=1) if multi_list else None
                    cls_token = pooled
                    full_features = None
                    
                elif model_type == 'sdxl_clip':
                    z, z_pool = model(dummy_img)
                    multi_cls = []
                    if intermediate_outputs:
                        for idx in sorted(intermediate_outputs.keys()):
                            out = intermediate_outputs[idx]
                            if out.dim() == 3 and out.shape[0] != dummy_img.shape[0]:
                                cls = out[0]
                            else:
                                cls = out[:, 0]
                            multi_cls.append(cls)
                        multi_features = torch.stack(multi_cls, dim=1)
                    else:
                        multi_features = None
                    cls_token = z_pool
                    full_features = z
            
            # Create memmap files based on dummy shapes
            out_pool_path = os.path.join(save_path, f'nsd_{file_prefix}_pool_{mode}_sub{subj}.npy')
            pool_mmap = np.lib.format.open_memmap(out_pool_path, mode='w+', dtype=np.float16, shape=(num_images, cls_token.shape[1]))
            
            token_mmap = None
            if config['has_tokens'] and full_features is not None:
                out_tokens_path = os.path.join(save_path, f'nsd_{file_prefix}_{mode}_sub{subj}.npy')
                token_mmap = np.lib.format.open_memmap(out_tokens_path, mode='w+', dtype=np.float16, shape=(num_images, full_features.shape[1], full_features.shape[2]))
                
            multi_mmap = None
            if multi_features is not None:
                out_multi_path = os.path.join(save_path, f'nsd_{file_prefix}{config["multi_suffix"]}{mode}_sub{subj}.npy')
                multi_shape_tuple = (num_images,) + multi_features.shape[1:]
                multi_mmap = np.lib.format.open_memmap(out_multi_path, mode='w+', dtype=np.float16, shape=multi_shape_tuple)
            
            for batch_i, batch_data in enumerate(dataloader):
                if batch_i % 10 == 0 or model_type == 'sam':
                    print(f"  Extracting Batch {batch_i}/{len(dataloader)} / {mode}...")
                    
                intermediate_outputs.clear()
                
                start_idx = batch_i * batch_size
                end_idx = min(start_idx + batch_data.shape[0], num_images)
                
                with torch.no_grad(), torch.amp.autocast('cuda', enabled=(device == 'cuda')):
                    batch_data = batch_data.to(device)
                    
                    if model_type == 'dinov2':
                        # Forward pass
                        output = model.forward_features(batch_data)
                        cls_token = output['x_norm_clstoken']
                        patch_tokens = output['x_norm_patchtokens']
                        
                        # Full features
                        full_features = torch.cat([cls_token.unsqueeze(1), patch_tokens], dim=1)
                        
                        # Multilayer CLS + patches
                        intermediate = model.get_intermediate_layers(batch_data, n=layers, reshape=False, return_class_token=True)
                        multi_features = torch.stack([
                            torch.cat([c.unsqueeze(1), p], dim=1) for p, c in intermediate
                        ], dim=1)
                        
                        pool_mmap[start_idx:end_idx] = cls_token.cpu().half().numpy()
                        if token_mmap is not None:
                            token_mmap[start_idx:end_idx] = full_features.cpu().half().numpy()
                        if multi_mmap is not None:
                            multi_mmap[start_idx:end_idx] = multi_features.cpu().half().numpy()
                        
                    elif model_type == 'resnet':
                        # Manual ResNet forward pass up to layer4/avgpool to align with hooks
                        x = model.conv1(batch_data)
                        x = model.bn1(x)
                        x = model.relu(x)
                        x = model.maxpool(x)
                        
                        x = model.layer1(x)
                        x = model.layer2(x)
                        x = model.layer3(x)
                        x = model.layer4(x)
                        
                        x_pool = model.avgpool(x)
                        x_pool = torch.flatten(x_pool, 1)
                        
                        # Process hooks
                        multi_features_list = []
                        for layer_name in layers:
                            feat = intermediate_outputs[layer_name]
                            feat_pool = F.adaptive_avg_pool2d(feat, (1, 1))
                            feat_pool = torch.flatten(feat_pool, 1)
                            
                            # Pad dimension to 2048 to allow stacking (B, 4, 2048)
                            pad_size = 2048 - feat_pool.shape[1]
                            if pad_size > 0:
                                    feat_pool = F.pad(feat_pool, (0, pad_size))
                            multi_features_list.append(feat_pool)
                            
                        multi_stack = torch.stack(multi_features_list, dim=1)
                        
                        pool_mmap[start_idx:end_idx] = x_pool.cpu().half().numpy()
                        if multi_mmap is not None:
                            multi_mmap[start_idx:end_idx] = multi_stack.cpu().half().numpy()
                        
                    elif model_type == 'sam':
                        outputs = model.vision_encoder(batch_data, output_hidden_states=True)
                        image_embeddings = outputs.last_hidden_state
                        pooled = F.adaptive_avg_pool2d(image_embeddings, (1, 1)).squeeze(-1).squeeze(-1)
                        
                        multi_list = []
                        for idx in layers:
                            if idx < len(outputs.hidden_states):
                                hidden_state = outputs.hidden_states[idx]
                                if hidden_state.dim() == 4:
                                    if hidden_state.shape[-1] == model.config.vision_config.hidden_size:
                                        hidden_state = hidden_state.permute(0, 3, 1, 2)
                                    layer_pooled = F.adaptive_avg_pool2d(hidden_state, (1, 1)).squeeze(-1).squeeze(-1)
                                elif hidden_state.dim() == 3:
                                    layer_pooled = hidden_state.mean(dim=1)
                                else:
                                    raise ValueError(f"Unexpected hidden state shape: {hidden_state.shape}")
                                multi_list.append(layer_pooled)
                                
                        if multi_list:
                            multi_stack = torch.stack(multi_list, dim=1)
                            if multi_mmap is not None:
                                multi_mmap[start_idx:end_idx] = multi_stack.cpu().half().numpy()
                            
                        pool_mmap[start_idx:end_idx] = pooled.cpu().half().numpy()
                        
                    elif model_type == 'sdxl_clip':
                        z, z_pool = model(batch_data)
                        
                        multi_cls = []
                        if intermediate_outputs:
                            for idx in sorted(intermediate_outputs.keys()):
                                out = intermediate_outputs[idx]
                                if out.dim() == 3 and out.shape[0] != batch_data.shape[0]:
                                    cls = out[0]
                                else:
                                    cls = out[:, 0]
                                multi_cls.append(cls)
                            multi_stack = torch.stack(multi_cls, dim=1)
                            if multi_mmap is not None:
                                multi_mmap[start_idx:end_idx] = multi_stack.cpu().half().numpy()
                            
                        pool_mmap[start_idx:end_idx] = z_pool.cpu().half().numpy()
                        if token_mmap is not None:
                            token_mmap[start_idx:end_idx] = z.cpu().half().numpy()
                        
                torch.cuda.empty_cache()
                
            # Flush changes and print summary
            pool_mmap.flush()
            del pool_mmap
            print(f"  ✅ Saved: {out_pool_path} (size={os.path.getsize(out_pool_path)/1e6:.1f}MB)")
            
            if token_mmap is not None:
                token_mmap.flush()
                del token_mmap
                print(f"  ✅ Saved: {out_tokens_path} (size={os.path.getsize(out_tokens_path)/1e6:.1f}MB)")
                
            if multi_mmap is not None:
                multi_mmap.flush()
                del multi_mmap
                print(f"  ✅ Saved: {out_multi_path} (size={os.path.getsize(out_multi_path)/1e6:.1f}MB)")
                    
    # Remove hooks at the end
    for h in hooks:
        h.remove()
        
    print(f"\n{'='*60}")
    print(f"Done. Feature extraction for model '{model_key}' completed successfully!")
    print(f"{'='*60}")

if __name__ == '__main__':
    main()
